web:
  restart: "always"
  build: ./webly
  expose:
    - "8000"
  links:
    - postgres:postgres
  env_file: .env
  command: "/usr/local/bin/gunicorn -w 2 -b :8000 api:app"

nginx:
  restart: "always"
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - ./app:/www/webly
  links:
    - web:web

data:
  restart: "no"
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  command: "true"

postgres:
  restart: "always"
  image: postgres:latest
  volumes_from:
    - data
  ports:
    - "5432:5432"
