#!/usr/bin/python3

import click
import logging
from webly.migrator.databasemanager import migrate
from webly.config import Config

@click.command()
def init():
    migrate()

if __name__ == '__main__':
    # Setup the logger configuration
    Config.setup_logger(level=logging.DEBUG)
    init()
