#!/usr/bin/python

import logging
import argparse
from web.migrator.databasemanager import DatabaseManager
from web.config import Config

class Webly():
    def __init__(self):
        self._log = logging.getLogger(__name__)
        self._lookup = {
            'db': {
                'init': DatabaseManager.init,
                'destroy': DatabaseManager.destroy,
                'migrate': DatabaseManager.migrate
            }
        }

    def run(self, section, command):
        '''
            Run the application
        '''
        self._log.info('Section: {0}'.format(section))
        self._log.info('Command: {0}'.format(command))
        self._lookup[section][command]()



if __name__ == '__main__':
    # Setup the logger configuration
    Config.setup_logger()

    # Parse the command line arguments
    parser = argparse.ArgumentParser(prog='PROG')
    subparsers = parser.add_subparsers()

    # Database management commands
    db_parser = subparsers.add_parser('db')
    db_parser.set_defaults(which='db')
    db_parser.add_argument('command', choices=['init', 'destroy','migrate'])

    args = parser.parse_args()
    Webly().run(args.which, args.command)
