#!/usr/bin/python3

import os
import click
import logging
from webly.database import drop, create
from webly.migrator import Migrator
from webly.config import Config


@click.command()
def init():
    drop()
    create()
    Migrator(os.path.join(os.path.dirname(__file__), 'sources.list')).run()

if __name__ == '__main__':
    # Setup the logger configuration
    Config.setup_logger(level=logging.DEBUG)
    init()
